{% set name = "atk" %}
{% set major_minor = "2.25" %}
{% set version = major_minor + ".90" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: http://ftp.gnome.org/pub/gnome/sources/{{ name }}/{{ major_minor }}/{{ name }}-{{ version }}.tar.xz
  sha256: 22d54c0ee7930c5906ab7d98e8711276edd2297c83bfd250ce471ff5e23e6094

build:
  number: 1003
  skip: True  # [win]
  detect_binary_files_with_prefix: true

requirements:
  build:
    - python >=3.6
    - perl
    - pkg-config
    - make
    - {{ compiler('c') }}
  host:
    - glib
    - gobject-introspection 1.*
  run:
    - glib
    - gobject-introspection 1.*

test:
  commands:
    - conda inspect linkages -p $PREFIX $PKG_NAME  # [not win]
    - conda inspect objects -p $PREFIX $PKG_NAME  # [osx]

about:
  home: http://www.gtk.org/
  license: LGPL-2.0
  license_file: COPYING
  summary: 'Accessibility Toolkit.'

extra:
  recipe-maintainers:
    - pkgw
    - ocefpaf
