travis:
  secure:
    BINSTAR_TOKEN: oy6Swa7eZWSR3Q6nOv+7GWThENd9q+Q+L00A8yZNwbaRq9Xo5aJKGTxp9q65OUX/PZ/HrhWJBYAyKb6Wkbeg1a6W7xexFMLgGyE51C3hIs/6iWnDzNEG/W7NSSd3qFhQfS7FSyrj3jbYhgRpOEbTIWyNLP29BKb9wuikdUE6rAJILQytNQfKea+9WbaqJVXX7DPlkjt5z12cyiEjWcNnU0VV9280G1sQFJhVxmFYQr7cgecT9qMOP2RyzcAMEv/1v49bGBpEu0y0blRqjJOj/ZpRbpSNmh1WN5GxiNxQ0bF5YrB/HkjiuPW4phuXXa8SbPRK5c9FEt6o0LclqeZDGt8loU8tbPCTEj82z3Z55AfR4wdYJw7FaQAem2iK6jcsUnEBz5BZ4Z9JsfRHNxmWP77qNpfHw/r3Matdiz9Wnqqm+ACBrwyBXTI+X1i+z58FVXSPG6bUsjv5QOD6DBzNO/CGm1zwRbVvVOsqcihIObHB2RVIz45e0hZonYA4o4HOTyHIj2YJkan5NOXPdzZHA213SyzLSljA/54BaicJLFHw/ZiN5DUCr/EzA+QXqo6xXC/GBsZG7xyLR9rIjQAzhxYzUwllsH4WEfo7c+hrN6Z+XjwsjvhSOxDVdkf3H2NG/CBqX0OFEe94PCk6tKgbOwpu5PE7VFRvP4KYz0sB+OY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
